server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
#    url : jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=demo
    username: yorkehan
    password: yorkehan
  redis:
    host: 45.32.137.229
    port: 6379
    password: admin
    database: 0
    timeout:
    jedis:
      pool:
        max-active: 100
        max-wait:
        max-idle: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yorkehan.pojo
logging:
  file: D:/Software/JetBrains/log/demo.log
  level:
    com.yorkehan.mapper: debug
pagehelper:
  helper-dialect: sqlserver2012


